import type { CSSProperties } from 'react'
import {
  ArrowRight,
  BedDouble,
  BookOpen,
  Bot,
  Building2,
  Bus,
  CalendarDays,
  CalendarPlus,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleStop,
  Clock,
  CloudRain,
  Compass,
  Copy,
  Crosshair,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Flame,
  Frown,
  Gamepad2,
  Hourglass,
  House,
  Image,
  Info,
  Landmark,
  LayoutGrid,
  Leaf,
  Lightbulb,
  List,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Meh,
  MessageCircle,
  MessageSquarePlus,
  Moon,
  Navigation,
  Coffee,
  PlusCircle,
  RefreshCw,
  Route,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingBag,
  Smile,
  Laugh,
  Sparkles,
  Star,
  Trash2,
  TreePine,
  TriangleAlert,
  User,
  Users,
  UtensilsCrossed,
  Video,
  Wallet,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

const appIcons = {
  addToPlan: PlusCircle,
  askAi: Sparkles,
  sparkles: Sparkles,
  arrowRight: ArrowRight,
  back: ChevronLeft,
  bot: Bot,
  cafe: Coffee,
  categoryActivity: Gamepad2,
  categoryCinema: Video,
  categoryHeritage: Building2,
  categoryKainan: UtensilsCrossed,
  categoryMall: ShoppingBag,
  categoryMuseum: Landmark,
  categoryNature: Leaf,
  categoryNightlife: Moon,
  categoryParke: TreePine,
  categoryStay: BedDouble,
  categoryTourist: Camera,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  clear: X,
  comments: MessageCircle,
  copy: Copy,
  directions: Route,
  email: Mail,
  eye: Eye,
  eyeOff: EyeOff,
  emptyPhoto: Image,
  photo: Image,
  book: BookOpen,
  bus: Bus,
  car: Car,
  fire: Flame,
  hourglass: Hourglass,
  info: Lightbulb,
  rain: CloudRain,
  users: Users,
  warning: TriangleAlert,
  galaPlan: Route,
  history: Clock,
  home: House,
  lock: Lock,
  logOut: LogOut,
  nearMe: Navigation,
  newChat: MessageSquarePlus,
  place: MapPin,
  profile: User,
  profileSearch: User,
  promptBuilder: Sparkles,
  promptBuilderAlt: FileText,
  refresh: RefreshCw,
  reports: Flag,
  reviews: Star,
  moodFrown: Frown,
  moodLaugh: Laugh,
  moodNeutral: Meh,
  moodSmile: Smile,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  uploadPhoto: Camera,
  map: Map,
  layoutGrid: LayoutGrid,
  list: List,
  filter: Filter,
  trash: Trash2,
  notice: Flag,
  tourist: MapPin,
  nearMeFixed: Crosshair,
  compass: Compass,
  calendarDays: CalendarDays,
  calendarPlan: CalendarPlus,
  check: Check,
  circleInfo: Info,
  circleStop: CircleStop,
  wallet: Wallet,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof appIcons

export type AppIconProps = {
  name: AppIconName
  size?: number
  className?: string
  style?: CSSProperties
  strokeWidth?: number
  'aria-label'?: string
}

/** Named lucide icons kept for older call sites; new code imports lucide icons directly. */
export function AppIcon({ name, size = 20, strokeWidth = 1.8, 'aria-label': ariaLabel, ...rest }: AppIconProps) {
  const Icon = appIcons[name]
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden={ariaLabel ? undefined : true} aria-label={ariaLabel} {...rest} />
}
