export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  "date-spot": [
    "date", "dates", "dating", "jowa", "jojowain", "couple", "couples",
    "romantic", "romance", "anniversary", "monthsary", "valentines",
    "valentine", "sweet", "cute date", "first date", "dinner date",
    "coffee date", "movie date", "walk date", "stroll date", "chill date",
    "date night", "pang date", "pang-date", "pang jowa", "pang couple",
    "with girlfriend", "with boyfriend", "with partner", "gf", "bf", "love",
    "lovey dovey",
  ],
  barkada: [
    "barkada", "friends", "friend", "tropa", "troops", "group", "squad",
    "gang", "peers", "classmates", "batchmates", "workmates", "coworkers",
    "team", "hangout", "hang out", "tambay with friends",
    "gala with friends", "bonding", "bonding place", "chikahan",
    "kwentuhan", "group date", "group activity", "with friends",
    "with tropa", "with barkada", "pang barkada", "pang tropa",
    "for friends", "friend group",
  ],
  family: [
    "family", "families", "parents", "parent", "mom", "mother", "dad",
    "father", "nanay", "tatay", "mama", "papa", "kids", "kid",
    "children", "child", "baby", "babies", "toddler", "senior", "seniors",
    "lolo", "lola", "grandparents", "with family", "with parents",
    "with kids", "family friendly", "kid friendly", "child friendly",
    "pang family", "pang pamilya", "pamilya", "family day",
    "family bonding", "safe for kids",
  ],
  "study-spot": [
    "study", "studying", "review", "reviewing", "schoolwork", "assignment",
    "homework", "research", "thesis", "capstone", "read", "reading",
    "quiet", "silent", "peaceful", "focus", "focused", "productive",
    "productivity", "laptop", "wifi", "wi-fi", "outlet", "charging",
    "work", "workplace", "work area", "study area", "study place",
    "study spot", "review center", "cram", "cramming", "pang study",
    "pang aral", "aral", "mag aral", "mag-aral", "gagawa schoolwork",
  ],
  coworking: [
    "coworking", "co-working", "workspace", "work space", "shared office",
    "office", "remote work", "work from home", "wfh", "freelance",
    "freelancer", "digital nomad", "meeting room", "conference room",
    "hot desk", "desk", "productive work", "workstation",
    "business meeting", "client meeting", "team meeting",
    "professional workspace", "work hub",
  ],
  cafe: [
    "cafe", "cafes", "coffee", "coffee shop", "coffeeshop", "kape",
    "kapihan", "espresso", "latte", "americano", "cappuccino", "frappe",
    "matcha", "tea", "milktea", "milk tea", "pastry", "pastries",
    "brunch cafe", "study cafe", "work cafe", "quiet cafe", "coffee date",
    "tambay cafe", "pang kape", "mag kape", "mag-kape", "caffeine",
  ],
  kainan: [
    "food", "foods", "eat", "eating", "kain", "kainan", "restaurant",
    "restaurants", "resto", "dining", "dine", "meal", "meals", "lunch",
    "dinner", "breakfast", "brunch", "snack", "snacks", "food trip",
    "foodtrip", "buffet", "samgyup", "samgyupsal", "hotpot", "ramen",
    "pizza", "burger", "chicken", "filipino food", "japanese food",
    "korean food", "chinese food", "street food", "fast food",
    "casual dining", "where to eat", "saan kakain", "kakain", "gutom",
    "pang kain", "pang dinner", "pang lunch",
  ],
  dessert: [
    "dessert", "desserts", "cake", "cakes", "ice cream", "icecream",
    "gelato", "donut", "donuts", "cookies", "cookie", "brownies",
    "brownie", "waffle", "waffles", "crepe", "crepes", "pastry",
    "pastries", "sweet", "sweets", "chocolate", "milkshake", "halo halo",
    "halo-halo", "bingsu", "cheesecake", "cupcake", "pang dessert",
    "after dinner", "matamis", "sweet cravings", "cravings",
  ],
  mall: [
    "mall", "malls", "shopping mall", "commercial center", "town center",
    "lifestyle mall", "plaza", "center", "aircon", "air conditioned",
    "indoor", "indoor place", "malling", "window shopping", "food court",
    "department store", "cinema mall", "pang mall", "gala sa mall",
    "tambay sa mall",
  ],
  shopping: [
    "shopping", "shop", "shops", "store", "stores", "buy", "bili",
    "mag shopping", "mag-shopping", "clothes", "clothing", "fashion",
    "shoes", "sneakers", "bags", "accessories", "gadgets", "electronics",
    "beauty products", "sale", "retail", "boutique", "department store",
    "window shopping", "pang shopping",
  ],
  market: [
    "market", "palengke", "tiangge", "bazaar", "flea market", "wet market",
    "dry market", "farmers market", "night market", "street market",
    "local market", "cheap finds", "budget shopping", "ukay", "ukay ukay",
    "ukay-ukay", "souvenirs", "local goods", "fresh produce", "bilihan",
    "mura", "bargain",
  ],
  cinema: [
    "cinema", "movie", "movies", "film", "films", "theater", "theatre",
    "watch movie", "watching movie", "movie date", "imax", "director's club",
    "screening", "blockbuster", "popcorn", "sine", "manood ng sine",
    "nood sine", "pang sine",
  ],
  "arcade-games": [
    "arcade", "arcades", "games", "gaming", "game", "play", "laro",
    "maglaro", "mag laro", "video games", "claw machine",
    "basketball arcade", "bowling", "billiards", "pool table", "karaoke",
    "ktv", "vr", "virtual reality", "escape room", "laser tag",
    "fun activities", "activities", "pang laro", "pang barkada activity",
  ],
  nightlife: [
    "nightlife", "night life", "bar", "bars", "pub", "club", "clubs",
    "drinks", "cocktails", "beer", "wine", "party", "partying", "inuman",
    "inom", "chillnuman", "night out", "late night", "live music", "dj",
    "rooftop bar", "speakeasy", "hangout at night", "pang gabi", "gabi",
    "after work drinks",
  ],
  chill: [
    "chill", "relax", "relaxing", "unwind", "tambay", "tambayan",
    "laid back", "calm", "peaceful", "quiet", "cozy", "cozy place",
    "slow day", "stroll", "walk", "lakad", "pasyal", "gala", "hangout",
    "hang out", "vibe", "good vibes", "aesthetic", "nice vibe",
    "chill vibes", "not crowded", "less crowded", "pang chill",
    "pang tambay",
  ],
  parke: [
    "park", "parks", "parke", "garden", "gardens", "green space",
    "open space", "outdoor", "outside", "nature", "trees", "grass",
    "picnic", "jog", "jogging", "walk", "walking", "stroll", "bike",
    "biking", "exercise outside", "fresh air", "playground", "public park",
    "pang picnic", "pasyal sa park",
  ],
  "tourist-spot": [
    "tourist", "tourist spot", "tourism", "tour", "tours", "sightseeing",
    "sight seeing", "landmark", "landmarks", "attraction", "attractions",
    "must visit", "must-see", "famous place", "popular place", "iconic",
    "instagrammable", "photo spot", "picture spot", "picture taking",
    "pasyalan", "galaan", "day tour", "tourist destination", "where to go",
    "saan pupunta", "visit",
  ],
  heritage: [
    "heritage", "historical", "history", "historic", "old place",
    "old building", "spanish era", "colonial", "cultural", "culture",
    "museum-like", "ancestral", "monument", "monuments", "fort",
    "walled city", "church history", "national history", "rizal",
    "intramuros", "old manila", "heritage site", "historical site",
    "pang history", "may history",
  ],
  museum: [
    "museum", "museums", "gallery", "galleries", "art gallery", "exhibit",
    "exhibition", "science museum", "art museum", "history museum",
    "interactive museum", "educational", "learn", "learning", "field trip",
    "school trip", "educational trip", "culture", "art", "artworks",
    "paintings", "installations", "pang museum", "pang educational",
  ],
  religious: [
    "church", "churches", "chapel", "cathedral", "basilica", "shrine",
    "temple", "mosque", "religious", "pray", "prayer", "worship", "mass",
    "misa", "simbang gabi", "visita iglesia", "holy", "spiritual",
    "pilgrimage", "retreat", "quiet prayer", "pang simba", "simba",
  ],
  "sports-fitness": [
    "sports", "sport", "fitness", "gym", "workout", "exercise", "training",
    "basketball", "volleyball", "badminton", "tennis", "football", "soccer",
    "swimming", "boxing", "martial arts", "yoga", "pilates", "running",
    "jogging", "cycling", "bike", "skating", "climbing", "court",
    "sports center", "fitness center", "pawis", "papawis", "pang workout",
  ],
  wellness: [
    "wellness", "spa", "massage", "relaxation", "self care", "self-care",
    "salon", "facial", "skin care", "skincare", "nails", "nail salon",
    "haircut", "barber", "barbershop", "beauty", "therapy", "sauna",
    "steam", "meditation", "mental wellness", "pamper", "pampering",
    "me time", "pang relax", "paganda",
  ],
  clinic: [
    "clinic", "clinics", "medical clinic", "doctor", "doctors", "checkup",
    "check up", "consultation", "health check", "laboratory", "lab test",
    "diagnostic", "urgent care", "healthcare", "medical", "pedia", "derma",
    "dermatology", "ob", "ent", "eye clinic", "consult", "pa checkup",
    "pa-checkup",
  ],
  dental: [
    "dental", "dentist", "dentists", "teeth", "tooth", "ngipin",
    "cleaning", "tooth cleaning", "braces", "orthodontics", "pasta",
    "bunot", "root canal", "wisdom tooth", "dental clinic", "oral care",
    "pa dentist", "pa cleaning ng teeth",
  ],
  pharmacy: [
    "pharmacy", "drugstore", "drug store", "medicine", "medicines", "meds",
    "gamot", "botika", "rx", "prescription", "vitamins", "supplements",
    "first aid", "health supplies", "buy medicine", "bili gamot",
    "pang gamot",
  ],
  hospital: [
    "hospital", "hospitals", "emergency", "er", "emergency room",
    "medical center", "health center", "admission", "surgery",
    "laboratory hospital", "urgent", "ambulance", "inpatient", "outpatient",
    "maternity", "major checkup", "ospital", "emergency care",
  ],
  transport: [
    "transport", "transportation", "terminal", "bus", "bus station", "jeep",
    "jeepney", "uv", "uv express", "train", "mrt", "lrt", "station",
    "taxi", "grab", "ride", "commute", "commuting", "parking", "car park",
    "airport", "ferry", "bike station", "sakayan", "babaan",
    "commute point",
  ],
  "pet-friendly": [
    "pet", "pets", "pet friendly", "pet-friendly", "dog", "dogs", "cat",
    "cats", "puppy", "kitten", "fur baby", "furbaby", "furparent",
    "fur parent", "pet cafe", "dog friendly", "cat friendly", "bring dog",
    "bring pet", "with dog", "with pet", "pet allowed", "pets allowed",
    "animal friendly", "pang pet",
  ],
  "hotel-stay": [
    "hotel", "hotels", "stay", "staycation", "stay cation", "overnight",
    "booking", "accommodation", "room", "rooms", "suite", "resort", "inn",
    "hostel", "bnb", "airbnb", "check in", "check-in", "lodge", "sleep",
    "rest overnight", "weekend stay", "pang staycation",
  ],
  services: [
    "service", "services", "repair", "fix", "maintenance", "laundry",
    "printing", "print", "photocopy", "xerox", "tailor", "alteration",
    "cleaning service", "car wash", "phone repair", "computer repair",
    "bank", "atm", "remittance", "government service", "documents",
    "id picture", "passport photo", "utility", "errands",
  ],
};

export const SEARCH_STOP_WORDS = [
  "place", "places", "spot", "spots", "near", "nearby", "around", "within",
  "find", "search", "looking", "look", "where", "where to", "saan", "san",
  "po", "please", "pls", "lang", "naman", "ba", "na", "ng", "sa", "in", "for",
  "with", "and", "or", "the", "a", "an", "me", "my", "kami", "ako", "ko",
  "namin", "natin", "gusto", "want", "need", "best", "good", "nice",
  "recommend", "recommendation", "suggest", "suggestion",
];
