export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  food: [
    "food", "foods", "eat", "eating", "kain", "kainan", "restaurant",
    "restaurants", "resto", "dining", "dine", "meal", "meals", "lunch",
    "dinner", "breakfast", "brunch", "snack", "snacks", "food trip",
    "foodtrip", "buffet", "samgyup", "samgyupsal", "hotpot", "ramen",
    "pizza", "burger", "chicken", "filipino food", "japanese food",
    "korean food", "chinese food", "street food", "fast food",
    "casual dining", "where to eat", "saan kakain", "kakain", "gutom",
    "pang kain", "pang dinner", "pang lunch", "dessert", "desserts",
    "ice cream", "halo halo", "halo-halo", "matamis", "sweet cravings",
  ],
  kainan: [
    "food", "foods", "eat", "eating", "kain", "kainan", "restaurant",
    "restaurants", "resto", "dining", "dine", "meal", "meals", "lunch",
    "dinner", "breakfast", "brunch", "snack", "snacks", "food trip",
    "foodtrip", "buffet", "samgyup", "samgyupsal", "hotpot", "ramen",
    "pizza", "burger", "chicken", "filipino food", "japanese food",
    "korean food", "chinese food", "street food", "fast food",
    "casual dining", "where to eat", "saan kakain", "kakain", "gutom",
    "pang kain", "pang dinner", "pang lunch", "dessert", "desserts",
    "ice cream", "halo halo", "halo-halo", "matamis", "sweet cravings",
  ],
  cafe: [
    "cafe", "cafes", "coffee", "coffee shop", "coffeeshop", "kape",
    "kapihan", "espresso", "latte", "americano", "cappuccino", "frappe",
    "matcha", "tea", "milktea", "milk tea", "pastry", "pastries",
    "brunch cafe", "study cafe", "work cafe", "quiet cafe", "coffee date",
    "tambay cafe", "pang kape", "mag kape", "mag-kape", "caffeine",
    "cake shop", "bakery", "bakeshop",
  ],
  mall: [
    "mall", "malls", "shopping mall", "commercial center", "town center",
    "lifestyle mall", "plaza", "center", "aircon", "air conditioned",
    "indoor", "indoor place", "malling", "window shopping", "food court",
    "department store", "cinema mall", "pang mall", "gala sa mall",
    "tambay sa mall",
  ],
  park: [
    "park", "parks", "parke", "garden", "gardens", "green space",
    "open space", "outdoor", "outside", "nature", "trees", "grass",
    "picnic", "jog", "jogging", "walk", "walking", "stroll", "bike",
    "biking", "fresh air", "playground", "public park", "pang picnic",
    "pasyal sa park",
  ],
  parke: [
    "park", "parks", "parke", "garden", "gardens", "green space",
    "open space", "outdoor", "outside", "nature", "trees", "grass",
    "picnic", "jog", "jogging", "walk", "walking", "stroll", "bike",
    "biking", "fresh air", "playground", "public park", "pang picnic",
    "pasyal sa park",
  ],
  museum: [
    "museum", "museums", "gallery", "galleries", "art gallery", "exhibit",
    "exhibition", "science museum", "art museum", "history museum",
    "interactive museum", "educational", "learn", "learning", "field trip",
    "school trip", "educational trip", "culture", "art", "artworks",
    "paintings", "installations", "pang museum", "pang educational",
  ],
  heritage: [
    "heritage", "historical", "history", "historic", "old place",
    "old building", "spanish era", "colonial", "cultural", "culture",
    "museum-like", "ancestral", "monument", "monuments", "fort",
    "walled city", "national history", "rizal", "intramuros", "old manila",
    "heritage site", "historical site", "pang history", "may history",
    "church", "chapel", "cathedral", "basilica", "shrine",
  ],
  tourist: [
    "tourist", "tourist spot", "tourism", "tour", "tours", "sightseeing",
    "sight seeing", "landmark", "landmarks", "attraction", "attractions",
    "must visit", "must-see", "famous place", "popular place", "iconic",
    "instagrammable", "photo spot", "picture spot", "picture taking",
    "pasyalan", "galaan", "day tour", "tourist destination", "where to go",
    "saan pupunta", "visit",
  ],
  date: [
    "date", "dates", "dating", "jowa", "jojowain", "couple", "couples",
    "romantic", "romance", "anniversary", "monthsary", "valentines",
    "valentine", "sweet", "cute date", "first date", "dinner date",
    "coffee date", "movie date", "walk date", "stroll date", "chill date",
    "date night", "pang date", "pang-date", "pang jowa", "pang couple",
    "with girlfriend", "with boyfriend", "with partner", "gf", "bf", "love",
    "lovey dovey",
  ],
  barkada: [
    "barkada", "friends", "friend", "tropa", "troops", "group", "squad",
    "gang", "peers", "classmates", "batchmates", "workmates", "coworkers",
    "team", "hangout", "hang out", "tambay with friends",
    "gala with friends", "bonding", "bonding place", "chikahan",
    "kwentuhan", "group date", "group activity", "with friends",
    "with tropa", "with barkada", "pang barkada", "pang tropa",
    "for friends", "friend group",
  ],
  family: [
    "family", "families", "parents", "parent", "mom", "mother", "dad",
    "father", "nanay", "tatay", "mama", "papa", "kids", "kid",
    "children", "child", "baby", "babies", "toddler", "senior", "seniors",
    "lolo", "lola", "grandparents", "with family", "with parents",
    "with kids", "family friendly", "kid friendly", "child friendly",
    "pang family", "pang pamilya", "pamilya", "family day",
    "family bonding", "safe for kids",
  ],
  study: [
    "study", "studying", "review", "reviewing", "schoolwork", "assignment",
    "homework", "research", "thesis", "capstone", "read", "reading",
    "quiet", "silent", "peaceful", "focus", "focused", "productive",
    "productivity", "laptop", "wifi", "wi-fi", "outlet", "charging",
    "work", "workplace", "work area", "study area", "study place",
    "study spot", "review center", "cram", "cramming", "pang study",
    "pang aral", "aral", "mag aral", "mag-aral", "gagawa schoolwork",
  ],
  chill: [
    "chill", "relax", "relaxing", "unwind", "tambay", "tambayan",
    "laid back", "calm", "peaceful", "quiet", "cozy", "cozy place",
    "slow day", "stroll", "walk", "lakad", "pasyal", "gala", "hangout",
    "hang out", "vibe", "good vibes", "aesthetic", "nice vibe",
    "chill vibes", "not crowded", "less crowded", "pang chill",
    "pang tambay",
  ],
  nightlife: [
    "nightlife", "night life", "bar", "bars", "pub", "club", "clubs",
    "drinks", "cocktails", "beer", "wine", "party", "partying", "inuman",
    "inom", "chillnuman", "night out", "late night", "live music", "dj",
    "rooftop bar", "speakeasy", "hangout at night", "pang gabi", "gabi",
    "after work drinks",
  ],
  arcade: [
    "arcade", "arcades", "games", "gaming", "game", "video games",
    "play", "bowling", "billiards", "karaoke", "ktv", "activity place",
    "fun games", "pang laro", "laro", "game night",
  ],
  cinema: [
    "cinema", "cinemas", "movie", "movies", "movie theater",
    "movie theatre", "film", "films", "imax", "screening", "watch movie",
    "manood sine", "sine", "movie date", "pang sine",
  ],
  hotel: [
    "hotel", "hotels", "staycation", "resort", "overnight", "accommodation",
    "room", "rooms", "suite", "suites", "vacation stay", "weekend stay",
    "romantic staycation", "family staycation",
  ],
  stay: [
    "hotel", "hotels", "staycation", "resort", "overnight", "accommodation",
    "room", "rooms", "suite", "suites", "vacation stay", "weekend stay",
    "romantic staycation", "family staycation",
  ],
};

export const SEARCH_STOP_WORDS = [
  "place", "places", "spot", "spots", "near", "nearby", "around", "within",
  "find", "search", "looking", "look", "where", "where to", "saan", "san",
  "po", "please", "pls", "lang", "naman", "ba", "na", "ng", "sa", "in", "for",
  "with", "and", "or", "the", "a", "an", "me", "my", "kami", "ako", "ko",
  "namin", "natin", "gusto", "want", "need", "best", "good", "nice",
  "recommend", "recommendation", "suggest", "suggestion",
];
